"""
FORTRESS v5 - deep_hedging.py
Path: models/hedging/deep_hedging.py

Deep Hedging Network.
Learns optimal cross-asset derivative hedges by minimizing Conditional Value at Risk (CVaR)
across the synthetic crash trajectories generated by the Neural SDE World Model.
Architecture ONLY. No training loops.
"""

import torch
import torch.nn as nn
import numpy as np
from typing import Dict, Tuple, List

class DeepHedgingNetwork(nn.Module):
    """
    Inputs:
        - z_t: 16-dim latent regime posterior
        - portfolio_state: [current_leverage, current_drawdown, unrealized_pnl]
        - alerts: [tda_wasserstein_alert (0/1), ltc_urgency_score (0-1)]
        
    Outputs:
        - Hedge overlay weights (h_t) for the proxy universe.
    """
    
    # Alpaca-compatible hedge proxy universe
    PROXY_UNIVERSE = [
        'VIXY', # Short-term VIX futures (Equity vol hedge)
        'GLD',  # Gold (Inflation / Safe haven)
        'TLT',  # Long duration Treasuries (Deflation / Flight to safety)
        'UUP',  # US Dollar Index (Global risk-off / EM stress)
        'SH'    # ProShares Short S&P 500 (Directional delta hedge)
    ]
    
    def __init__(self, config: Dict):
        super().__init__()
        
        self.regime_dim = config.get('latent_dim', 16)
        self.portfolio_dim = 3
        self.alert_dim = 2
        
        self.input_dim = self.regime_dim + self.portfolio_dim + self.alert_dim
        self.output_dim = len(self.PROXY_UNIVERSE)
        self.hidden_dim = config.get('hedging_hidden_dim', 128)
        
        # The network that predicts the optimal hedge overlay
        self.net = nn.Sequential(
            nn.Linear(self.input_dim, self.hidden_dim),
            nn.LayerNorm(self.hidden_dim),
            nn.Mish(),
            nn.Linear(self.hidden_dim, self.hidden_dim // 2),
            nn.Mish(),
            nn.Linear(self.hidden_dim // 2, self.output_dim),
            nn.Sigmoid() # Outputs raw activation between [0, 1] for each proxy
        )

    def forward(self, state_vector: torch.Tensor) -> torch.Tensor:
        """
        Forward pass returning raw hedge activations.
        """
        return self.net(state_vector)

    @torch.no_grad()
    def get_hedge_overlay(self, z_t: np.ndarray, portfolio_state: np.ndarray, 
                          tda_alert: bool, ltc_urgency: float, 
                          crash_probability: float, max_leverage: float = 1.5) -> Dict[str, float]:
        """
        LIVE INFERENCE METHOD.
        Called by services/portfolio_agent_svc.py to overlay protective weights
        onto the EDT's base portfolio allocation.
        
        Returns:
            Dictionary mapping proxy tickers to their target portfolio weights.
        """
        self.eval()
        
        # 1. Check Activation Triggers
        # Hedging costs money (spread, drag). We only activate if a threat is detected.
        if crash_probability < 0.20 and not tda_alert and ltc_urgency < 0.80:
            return {ticker: 0.0 for ticker in self.PROXY_UNIVERSE}
            
        # 2. Construct State
        alerts = np.array([float(tda_alert), ltc_urgency], dtype=np.float32)
        state = np.concatenate([z_t, portfolio_state, alerts])
        state_tensor = torch.FloatTensor(state).unsqueeze(0)
        
        # 3. Predict Raw Hedge Weights
        raw_weights = self.forward(state_tensor).squeeze(0).numpy()
        
        # 4. Apply Budget & Constraints
        # Total hedge size scales with the severity of the alerts
        urgency_multiplier = max(crash_probability, float(tda_alert), ltc_urgency)
        
        # Assume a max hedge budget of 30% of portfolio value (adjust via config)
        max_hedge_budget = 0.30 * urgency_multiplier
        
        # Normalize and scale weights
        weight_sum = np.sum(raw_weights) + 1e-8
        scaled_weights = (raw_weights / weight_sum) * max_hedge_budget
        
        hedge_dict = {ticker: float(weight) for ticker, weight in zip(self.PROXY_UNIVERSE, scaled_weights)}
        
        # 5. CRITICAL: The Contango Constraint
        # VIXY suffers from severe roll yield decay. 
        # If systemic crash probability is not absolute (>90%), restrict VIXY to 0.0 here.
        # Intraday VIXY scalping is handled purely by the URGENT-DDPG agent, not this overnight holding layer.
        if crash_probability < 0.90:
            hedge_dict['VIXY'] = 0.0
            
        # Cap SH (Short S&P) to prevent accidental net-short exposure violating mandate
        hedge_dict['SH'] = min(hedge_dict['SH'], 0.15)
        
        return hedge_dict

    def compute_cvar_loss(self, predicted_hedges: torch.Tensor, simulated_portfolio_returns: torch.Tensor, 
                          simulated_proxy_returns: torch.Tensor, alpha: float = 0.05) -> torch.Tensor:
        """
        Training loss function.
        Minimizes the 5% Conditional Value at Risk (CVaR) of the hedged portfolio
        across the World Model's synthetic trajectories.
        """
        # Calculate fully hedged returns: Base_Return + sum(Hedge_Weight * Proxy_Return)
        hedge_pnl = torch.sum(predicted_hedges.unsqueeze(1) * simulated_proxy_returns, dim=-1)
        total_returns = simulated_portfolio_returns + hedge_pnl
        
        # Sort returns to find the worst tail (the alpha percentile)
        sorted_returns, _ = torch.sort(total_returns, dim=-1)
        tail_idx = int(alpha * total_returns.shape[-1])
        
        # CVaR is the expected value of the returns strictly worse than the VaR threshold
        worst_cases = sorted_returns[:, :tail_idx]
        cvar = worst_cases.mean(dim=-1)
        
        # Add a L1 penalty for the hedge weights (hedging isn't free, penalize over-hedging)
        cost_penalty = 0.01 * torch.sum(predicted_hedges, dim=-1)
        
        # We want to MAXIMIZE the CVaR (make the worst-case less negative), so we minimize the negative CVaR
        loss = -cvar + cost_penalty
        return loss.mean()